GET http://localhost:5000/helo

###register route
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email":"roheet@example.com",
    "password":"qwertyuiop",
    "firstName": "Roheet",
    "lastName": "Basukala",
    "phone": "9877667755",
    "role":"admin"

}

###login route 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"roheet@example.com",
    "password":"qwertyuiop"

}

###logout route 
DELETE  http://localhost:5000/api/auth/logout


###userRoutes
GET http://localhost:5000/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjgwMWQ2MTBlNzUwZmJkZjU1NzMwMyIsInJvbGUiOiJwaGFybWFjaXN0IiwiaWF0IjoxNzUxNjg3MTA0LCJleHAiOjE3NTE2OTA3MDR9.eNz0u4KYqgx-Uod-DHEk68u7t80spMcsubvwXlYHi3o
###
GET http://localhost:5000/api/users/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjgwMWQ2MTBlNzUwZmJkZjU1NzMwMyIsInJvbGUiOiJwaGFybWFjaXN0IiwiaWF0IjoxNzUxNjg3MjQ0LCJleHAiOjE3NTE2OTA4NDR9.gm-MkvmObKxi3ALB1fSHgoQLf1nq7kbmdFfoDwyN3SU









###medicine Routes

### get all medicine 
GET http://localhost:5000/api/medicine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcxMzE2MywiZXhwIjoxNzUxNzE2NzYzfQ.3iYzvYKi9us1LyqnqHzwZTxWBTCgc8uVBkh-vtECneE

### add the medicine 
POST http://localhost:5000/api/medicine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3Mzk5NSwiZXhwIjoxNzUxOTc3NTk1fQ.bW9cmGySfZp9fUwhdRoi4kJFrv1OwoQN63tyFwBA1dY
Content-Type: application/json

{
  "medicineName": "TestMed ExpireSoon",
  "genericName": "TestGen",
  "manufacturer": "TestPharma",
  "dosageForm": "tablet",
  "qrCode": "TEST-EXP",
  "minThreshold": 20
}



### get medicine by id 
GET http://localhost:5000/api/medicine/686d0130c305dc5df330526f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3Mzk5NSwiZXhwIjoxNzUxOTc3NTk1fQ.bW9cmGySfZp9fUwhdRoi4kJFrv1OwoQN63tyFwBA1dY


### update medicine
PATCH http://localhost:5000/api/medicine/6868d64d203f18ad471af30b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcxNjk4NiwiZXhwIjoxNzUxNzIwNTg2fQ.tQ6chWDVCBAtfNWLk1lff3E2UtedhCnkW0_OUkPW6ow
Content-Type: application/json

{
  
}

### delete medicine
DELETE  http://localhost:5000/api/medicine/6869217851053b07c9768c67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcyMDExMiwiZXhwIjoxNzUxNzIzNzEyfQ.uJGWCdCo8unuK7LYrYLTTAzsr-EigxPmsA66oVg1f18





###batch Routes 
POST http://localhost:5000/api/batches
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3Mzk5NSwiZXhwIjoxNzUxOTc3NTk1fQ.bW9cmGySfZp9fUwhdRoi4kJFrv1OwoQN63tyFwBA1dY
Content-Type: application/json

{
  "medicine": "686d0130c305dc5df330526f",  
  "batchNumber": "EXP-14",
  "expiryDate": "2025-07-22",  
  "quantity": 50
}


### getBatchByMedicine
GET http://localhost:5000/api/batches/medicine/686d0130c305dc5df330526f
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3Mzk5NSwiZXhwIjoxNzUxOTc3NTk1fQ.bW9cmGySfZp9fUwhdRoi4kJFrv1OwoQN63tyFwBA1dY


###get Expiring batches 
GET http://localhost:5000/api/batches/expiring-soon?days=14
authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3NjA3MSwiZXhwIjoxNzUxOTc5NjcxfQ.NNGL3X8xuYTuZ6dzkGYFSt0DBLfQ-X1ppz1NmENE6Vg

###update batch 
PATCH http://localhost:5000/api/batches/686d0233c305dc5df3305272
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk3NjA3MSwiZXhwIjoxNzUxOTc5NjcxfQ.NNGL3X8xuYTuZ6dzkGYFSt0DBLfQ-X1ppz1NmENE6Vg
Content-Type: application/json

{
  "expiryDate": "2025-07-25T00:00:00.000Z",
  "quantity": 100
}