GET http://localhost:5000/helo

###register route
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email":"roheet@example.com",
    "password":"qwertyuiop",
    "firstName": "Roheet",
    "lastName": "Basukala",
    "phone": "9877667755",
    "role":"admin"

}

###login route 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"roheet@example.com",
    "password":"qwertyuiop"

}

###logout route 
DELETE  http://localhost:5000/api/auth/logout


###userRoutes
GET http://localhost:5000/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjgwMWQ2MTBlNzUwZmJkZjU1NzMwMyIsInJvbGUiOiJwaGFybWFjaXN0IiwiaWF0IjoxNzUxNjg3MTA0LCJleHAiOjE3NTE2OTA3MDR9.eNz0u4KYqgx-Uod-DHEk68u7t80spMcsubvwXlYHi3o
###
GET http://localhost:5000/api/users/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjgwMWQ2MTBlNzUwZmJkZjU1NzMwMyIsInJvbGUiOiJwaGFybWFjaXN0IiwiaWF0IjoxNzUxNjg3MjQ0LCJleHAiOjE3NTE2OTA4NDR9.gm-MkvmObKxi3ALB1fSHgoQLf1nq7kbmdFfoDwyN3SU









###medicine Routes

### get all medicine 
GET http://localhost:5000/api/medicine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcxMzE2MywiZXhwIjoxNzUxNzE2NzYzfQ.3iYzvYKi9us1LyqnqHzwZTxWBTCgc8uVBkh-vtECneE

### add the medicine 
POST http://localhost:5000/api/batches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTgwODI1NSwiZXhwIjoxNzUxODExODU1fQ.qLYvjEzT_KriPMDhHsheumcmopBGYbJj_l-Pvufgt4s 
Content-Type: application/json

{
  "medicineName": "Pantop",
  "genericName": "panzol",
  "manufacturer": "Nepal Pharma Ltd.",
  "dosageForm": "syrup",
  "qrCode": "QR1234567890ABCDEFhd",
  "minThreshold": 50
}


### get medicine by id 
GET http://localhost:5000/api/medicine/6868d64d203f18ad471af30b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcxMzE2MywiZXhwIjoxNzUxNzE2NzYzfQ.3iYzvYKi9us1LyqnqHzwZTxWBTCgc8uVBkh-vtECneE


### update medicine
PATCH http://localhost:5000/api/medicine/6868d64d203f18ad471af30b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcxNjk4NiwiZXhwIjoxNzUxNzIwNTg2fQ.tQ6chWDVCBAtfNWLk1lff3E2UtedhCnkW0_OUkPW6ow
Content-Type: application/json

{
  
}

### delete medicine
DELETE  http://localhost:5000/api/medicine/6869217851053b07c9768c67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTcyMDExMiwiZXhwIjoxNzUxNzIzNzEyfQ.uJGWCdCo8unuK7LYrYLTTAzsr-EigxPmsA66oVg1f18





###batch Routes 
POST http://localhost:5000/api/batches
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Njg4MWU4YmY3MzA1OTQ5M2UyNTE0MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTgxMjQzMiwiZXhwIjoxNzUxODE2MDMyfQ.ypGuppiGydbG82LUgvgDTFpuK8RtWXVF6O2sCfPYjyE 
Content-Type: application/json

{
  "medicine": "6869219d51053b07c9768c6b",
  "batchNumber": "BATCH-2307",
  "expiryDate": "2025-07-31",
  "quantity": 100,
  "createdBy": "686881e8bf73059493e25141"
}
